name: Build

on: [push, pull_request]

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
         mkdir build
         cd build
         cmake ..
         sudo make -j16

  buildOSX:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
         cd vt
         make CLANG=Y demos

  buildWindows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd wingui
        nmake UTF8=Y DLL=Y -f Makefile.vc demos
        cd ..\wincon
        nmake DLL=Y -f Makefile.vc demos
        cd ..\vt
        nmake CHTYPE_32=Y -f Makefile.vc demos
      shell: cmd
